CREATE TABLE TBPESSOA (
    PESCODIGO SERIAL PRIMARY KEY,
    PESNOME VARCHAR(150) NOT NULL,
    PESSOBRENOME VARCHAR(150),
    PESEMAIL VARCHAR(150),
    PESPASSWORD TEXT,
    PESCIDADE VARCHAR(100),
    PESESTADO VARCHAR(2)
);
